apiVersion: "config.istio.io/v1alpha2"
kind: denier
metadata:
  name: denyall
spec:
  status:
    code: 7
    message: Not allowed
---
apiVersion: "config.istio.io/v1alpha2"
kind: checknothing
metadata:
  name: denyrequest
spec:
 
---
apiVersion: "config.istio.io/v1alpha2"
kind: rule
metadata:
  name: mixerdenysome
spec:
  match: match(request.headers["user-agent"], "curl*")
  actions:
  - handler: denyall.denier
    instances: [ denyrequest.checknothing ]
