apiVersion: "v1"
kind: "Service"
metadata:
  name: "pubsub-proxy"
  namespace: "default"
  labels:
    app: "pubsub-proxy"
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: "pubsub-proxy"

---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "pubsub-proxy"
  namespace: "default"
  labels:
    app: "pubsub-proxy"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "pubsub-proxy"
  template:
    metadata:
      labels:
        app: "pubsub-proxy"
        version: v1
    spec:
      volumes:
      - name: google-cloud-key
        secret:
          secretName: clientsecret
      containers:
      - name: "pubsub-proxy"
        image: "gcr.io/[PROJECT_ID]/pubsub-proxy:latest"
        volumeMounts:
        - name: google-cloud-key
          mountPath: /var/secrets/google
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/key.json
        - name: CLIENTID
          valueFrom:
            secretKeyRef:
              name: clientsecret
              key: clientid
        ports:
        - containerPort: 8080
---
apiVersion: "autoscaling/v1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "pubsub-proxy-hpa"
  namespace: "default"
  labels:
    app: "pubsub-proxy"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "pubsub-proxy"
    apiVersion: "apps/v1beta1"
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: pubsub-proxy-gateway
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
      privateKey: /etc/istio/ingressgateway-certs/tls.key
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: pubsub-proxy
spec:
  hosts:
  - "*"
  gateways:
  - pubsub-proxy-gateway
  http:
  - route:
    - destination:
        port:
         number: 8080
        host: pubsub-proxy
    retries:
      attempts: 3
      perTryTimeout: 2s
